### ISSUE TITLE
[Bug] Connection to nats with macos and mobile

### ISSUE THREAD

**Issue by ngoluuduythai** [chartchuo/dart-nats#22]
When connect to `nats://demo.nats.io` in macOS and mobile, I have this error
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (start): Invalid value: Only valid value is 0: 2
#0      RangeError.checkValidRange (dart:core/errors.dart:358:7)
#1      _TypedIntListMixin.sublist (dart:typed_data-patch/typed_data_patch.dart:463:31)
#2      Client._sign (package:nats_test/src/client.dart:118:21)
#3      Client._processOp (package:nats_test/src/client.dart:414:15)
#4      Client._steamHandle.<anonymous closure> (package:nats_test/src/client.dart:158:9)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#8      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#10     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

```
After that, I try to comment on this code 
`await _sign();`
The connection will be connected

**Comment by chartchuo** [comment]
Thank for submit bug. I change _sign() as following
```
 Future _sign() async {
    if (_info.nonce != null && seed != '') {
      var nkeys = await Nkeys.fromSeed(seed);
      var sig = await nkeys.sign(utf8.encode(_info.nonce ?? ''));

      _connectOption.sig = base64.encode(sig.bytes);
    }
  }
```
will update in version 0.4.9
